//
//  LocalizationText.swift
//  learn_japanese
//
//  Created by Hưng Hà Quang on 21/7/24.
//

import Foundation
import L10n_swift

class LocalizationText {
    static let login = "login".l10n()
    static let signUp = "signUp".l10n()
    static let userName = "userName".l10n()
    static let emailAddress = "emailAddress".l10n()
    static let password = "password".l10n()
    static let forgotPassword = "forgotPassword".l10n()
    static let or = "or".l10n()
    static let loginWithGoogle = "loginWithGoogle".l10n()
    static let loginWithFacebook = "loginWithFacebook".l10n()
    static let loginWithApple = "loginWithApple".l10n()
    static let passwordRequirement1 = "passwordRequirement1".l10n()
    static let passwordRequirement2 = "passwordRequirement2".l10n()
    static let passwordRequirement3 = "passwordRequirement3".l10n()
    static let yourCurrentJapaneseLevel = "yourCurrentJapaneseLevel".l10n()
    static let loginError = "loginError".l10n()
    static let signOut = "signOut".l10n()
    static let sendMailError = "sendMailError".l10n()
    static let signUpError = "signUpError".l10n()
    static let sendEmail = "sendEmail".l10n()
    static let sentEmail = "sentEmail".l10n()
    static let emailSentSuccessfully = "emailSentSuccessfully".l10n()
    static let next = "next".l10n()
    static let startJapanese = "startJapanese".l10n()
    static let basicJapanese = "basicJapanese".l10n()
    static let intermediateJapanese = "intermediateJapanese".l10n()
    static let startJapaneseDescription = "startJapaneseDescription".l10n()
    static let basicJapaneseDescription = "basicJapaneseDescription".l10n()
    static let intermediateJapaneseDescription = "intermediateJapaneseDescription".l10n()
    static let learn = "learn".l10n()
    static let review = "review".l10n()
    static let dictionary = "dictionary".l10n()
    static let profile = "profile".l10n()
    static let lesson = "lesson".l10n()
    static let dontQuit = "dont_quit".l10n()
    static let almostDone = "almost_done".l10n()
    static let continueLearning = "continue_learning".l10n()
    static let finish = "finish".l10n()
    static let correctAnswer = "correctAnswer".l10n()
    static let wrongAnswer = "wrongAnswer".l10n()
    static let tryAgain = "tryAgain".l10n()
    static let needImprovement = "needImprovement".l10n()
    static let fair = "fair".l10n()
    static let good = "good".l10n()
    static let excellent = "excellent".l10n()
    static let correctAnswerMessage = "correctAnswerMessage".l10n()
    static let correctAnswerPrefix = "correctAnswerPrefix".l10n()
    static let incorrect = "incorrect".l10n()
    static let correct = "correct".l10n()
    static let continueMessage = "continue".l10n()
    static let notYetLearned = "notYetLearned".l10n()
    static let learned = "learned".l10n()
    static let confirm = "confirm".l10n()
    static let saveProfileChanges = "saveProfileChanges".l10n()
    static let logout = "logout".l10n()
    static let cancel = "cancel".l10n()
    static let doYouWantLogout = "doYouWantLogout".l10n()
    static let recommendReview = "recommendReview".l10n()
    static let reviewSuggestionMessage = "reviewSuggestionMessage".l10n()
    static let accuracyRate = "accuracyRate".l10n()
}
